---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.8
  - 2.2.4
script:
  - bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.3.2"
